name: Deploy to VPS
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Upload code
        uses: actions/checkout@v4

      - name: Configure SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
        shell: bash

      - name: Deploy to server
        env:
          HOST: ${{ secrets.HOST }}
          USER: ${{ secrets.USERNAME }}
          APP_DIR: /online_card
          PORT: ${{ secrets.PORT }}
        run: |
          ssh-keyscan -H $HOST >> ~/.ssh/known_hosts
          ssh $USER@$HOST "
            if [ ! -d $APP_DIR ]; then
              mkdir -p $APP_DIR
              git clone https://github.com/Shaxriyor0428/Online-card-booking.git $APP_DIR
              cd $APP_DIR
              echo 'PORT=${PORT}
              PG_DB=${{ vars.PG_DB }}
              PG_HOST=${{ vars.PG_HOST }}
              PG_PASS=${{ vars.PG_PASS }}
              PG_PORT=${{ vars.PG_PORT }}
              PG_USER=${{ vars.PG_USER }}' > .env
            else 
              cd $APP_DIR
              git pull origin main 
            fi
            npm install
            npm run build
            pm2 restart online_card || pm2 start dist/main.js --name online_card
          "
        shell: bash
